version: "3"
services:
    app:
        container_name: app
        build: .
        restart: always
        ports: 
            - 3000:3000
        links: 
          - db
        environment:
            PORT: 3000
            MONGO_URI: mongodb://db:27017/users_db
    db:
        container_name: db
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - 27018:27017
